### ISSUE TITLE
Integration usa contacts info into FOIA

### ISSUE THREAD

**Issue by jackiekazil** [18F/foia-hub#142]
This ticket of tickets to ensure that all work discussed relating to the usa contacts integration is completed. 
- [x] #143 - Restructure usa-contacts & contacts folder in /foia repo (required)
- [x] #144 - Generate initial list of proposed matches usa-agency to foia-agency in db
- [x] #145 - Review the proposed matches usa-agency to foia-agency to make sure there are not errors
- [x] #146 - Update foia-agency in YAMLs to include usa contact information
- [x] #147 - Update the contacts loader to load new data points stored in the yamls into the db

Not in this sprint:
- Integrating parent ids 
- #120 Check for child agencies that do not exist in the database
